### ISSUE TITLE
No one can login with Facebook

### ISSUE THREAD

**Issue by unicodeveloper** [andela-doladosu/opencasts#6]
I think your facebook app is still in sandbox mode, so when someone wants to login..this is what it brings up!

<img width="1235" alt="screen shot 2015-10-25 at 10 52 26 pm" src="https://cloud.githubusercontent.com/assets/2946769/10718125/3287e20e-7b6b-11e5-8641-6a39ccb908a7.png">

It doesn't go past that. Please check it out and fix ASAP!

**Comment by dara-tobi** [comment]
I had no idea about this. It worked fine for me and I assumed it would work fine for everyone else. It's fixed now. All Facebook addicts can now login with their preferred option.
